theme="material-design"
#baseurl = "http://gileshuang.github.io"
baseurl = "https://blog.systemctl.top"
languageCode = "zh-cn"
title = "黄家垚的主页"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
#disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Copyleft Text"

[params]
  description = "我的第一个个人页面" # optional
  twitter = "giles_huang" # optional
  github = "gileshuang" # optional
  weibo = "jiayaohuang1992" # optional
  gitosc = "aliendata" # optional
  facebook = "huangjiayao" # optional
#  gplus = "Your Google+ profile name" # optional
#  linkedin = "Your LinkedIn Name" # optional

   # Gitment, optional
  gitment_owner = "gileshuang" # optional
  gitment_repo = "gileshuang.github.io"
  gitment_clientid = "30408b4f6463ecaf5d87"
  gitment_clientsecret = "a81c6cda52d080e18f7a49762f625407d50b1815"

#  headerCover = "images/headerCover.png" # optional
#  footerCover = "images/footerCover.png" # optional
#  googleAnalyticsUserID = "Your Analytics User Id" # optional

[gitment]
  owner = "gileshuang"

[permalinks]
#  post = "/:year/:month/:day/:title/" # optional
  post = "/:year/:filename/" # optional

